# Fabric Properties
	# check these on https://fallen-breath.github.io/fabric-versions/?version=26.2
	minecraft_version=26.2
	parchment_version=

# Fabric Mod Metadata
	minecraft_dependency=>=26.2 <26.3
	malilib_dependency=>=0.29.3
	modmenu_dependency=>=20.0.1

# Build Information
	# The target mc versions for the mod during mod publishing, separated with \n
	game_versions=26.2

# Dependencies
	malilib_jar=malilib-fabric-26.2-0.29.3.jar
	modmenu_jar=modmenu-20.0.1.jar